const characterTitles = {
    diganyu: "循循守月",
    dichongyue: "自晦及明",
    diren: "死兆将至",
    diluocha: "寻索世间",
    dinaxida: "白草净华",
    dihuangquan: "远辞畴昔",
    dimaenna: "未曾起誓",
    diqinliu: "小丘上的眠柳",
    dijingmolieshou: "狩猎之影",
    dikirito: "黑色剑士",
    dikokomi: "真珠之智",
    ditaojinniang: "浮光跃金",
    jie_diganyu: "循循守月",
    dibanzang: "巨龙之魂",
    dizhongli: "尘世闲游",
    di5t5: "会赢的",
    jie_dichongyue: "自晦及明",
    diayfl: "火舞之人",
    dimulikong: "？？？",
    disrtr: "无拘熔火",
    dijicanghai: "『烈豪』",
    dirobin: "翼声纯律",
    diyftx: "白色怪物",
    dizxskd: "深悼",
    dizxj: "？？？",
    difuxuan: "穷观妙算",
    dishenzhuri: "齐响诗班",
    difellowhuisheng: "齐响诗班",
};
export default characterTitles;